name: presentation
description: Presentation layer
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  firebase_core: ^1.13.1
  firebase_analytics: ^8.3.4
  firebase_crashlytics: ^2.3.0
  firebase_database: ^8.1.0
  firebase_messaging: ^11.2.11
  cloud_firestore: ^3.1.10

  data:
    path: ../data